const FEATURES = {
  "plant-0": "getrennte Sprosse: braune Sporenähren früh, grüne Quirltriebe später; hohl gegliedert; Äcker, Wege",
  "plant-1": "fein mehrfach verzweigte, hängende Quirlläste; Sporenähre an grünem Spross; feuchte Wälder",
  "plant-2": "riesige dreieckige Wedel einzeln aus Rhizom; harte Stiele; dichte Bestände; saure Wälder, Heiden",
  "plant-3": "zarte hellgrüne 2-3fach gefiederte Wedel; kommaförmige Sori; feuchte schattige Wälder",
  "plant-4": "schmale Wedel, dornig gezähnt; Stielschuppen einfarbig hellbraun; feuchte saure Wälder, Moore",
  "plant-5": "breit dreieckige Wedel, stark geteilt; Stielschuppen dunkel gestreift; saure feuchte Wälder",
  "plant-6": "kräftiger Trichter; Wedel lanzettlich; runde Sori zweireihig; braune Schuppen; Laubwälder",
  "plant-7": "flache weiche Nadeln, 2 weiße Unterseitenstreifen, Spitze oft gekerbt; Zapfen aufrecht, zerfallend",
  "plant-8": "weiche Nadeln, zerrieben orangig; hängende Zapfen mit 3-zackigen Deckschuppen",
  "plant-9": "stechende 4-kantige Nadeln ringsum; hängende Zapfen fallen ganz; Zweige mit rauen Nadelkissen",
  "plant-10": "weiche Nadeln in Büscheln, sommergrün; kleine aufrechte Zapfen; Herbst goldgelb",
  "plant-11": "Nadeln paarweise, blaugrün gedreht; orange obere Borke; trockene sandige Standorte",
  "plant-12": "gelbe kugelige Blüten; große schwimmende Herzblätter; Teiche, Altwasser",
  "plant-13": "weiße vielblättrige Blüten mit gelbem Zentrum; runde Schwimmblätter mit tiefer Kerbe",
  "plant-14": "früher Waldteppich; 1 weiße Blüte; 3 quirlige, handteilige Hochblätter; Laubwald",
  "plant-15": "glänzende nierenförmige Blätter; große gelbe 5-teilige Blüten; nasse Wiesen, Gräben",
  "plant-16": "früh gelbe Sternblüten; glänzende herz-nierenförmige Blätter; später einziehend; Auen, Gärten",
  "plant-17": "aufrecht, keine Ausläufer; tief handgeteilte Blätter; glänzend gelbe Blüten; Wiesen",
  "plant-18": "kriechende wurzelnde Ausläufer; dreiteilige Blätter; gelbe Blüten; feuchte Trittstellen",
  "plant-19": "gelber Milchsaft; gelbe 4-Kronblatt-Blüten; blaugrün gelappte Blätter; Mauern, Säume",
  "plant-20": "rote 4 Blütenblätter oft schwarzer Grundfleck; behaarte Stängel; Porenkapsel; Äcker",
  "plant-21": "glatte graue Borke; ovale gewellte Blätter mit Wimperrand; Bucheckern; schattige Wälder",
  "plant-22": "Blätter lang gestielt, Basis keilförmig; Eicheln fast sitzend; trockene Wälder",
  "plant-23": "Blattstiel sehr kurz, Blattbasis geöhrt; Eicheln lang gestielt; Auen, frische Böden",
  "plant-24": "große spitz gelappte Blätter mit Borstenspitzen; rote Herbstfarbe; flache Fruchtbecher",
  "plant-25": "weiße abblätternde Borke mit schwarzen Rissen; hängende Zweige; dreieckige gesägte Blätter",
  "plant-26": "runde Blätter mit eingekerbter Spitze; junge Blätter klebrig; kleine schwarze Zapfen; Bachufer",
  "plant-27": "grauer geflammter Spannrücken-Stamm; gefaltete doppelt gesägte Blätter; 3-lappige Fruchtbrakteen",
  "plant-28": "runde herzförmige raue Blätter; frühe Kätzchen; Nüsse in grüner Hülle; Hecken",
  "plant-29": "sehr raue große Blätter, Basis stark asymmetrisch; kurze Stiele; runde Flügelfrüchte",
  "plant-30": "gegenständige gesägte Brennhaare-Blätter; Stängel vierkantig; nährstoffreiche Säume",
  "plant-31": "schmale grasartige Blätter; weiße tief gespaltene Blüten; lockerer Wuchs; magere Wiesen",
  "plant-32": "niedrige Matten; Stängel mit 1 Haarlinie; kleine weiße Spaltblüten; Gärten, Äcker",
  "plant-33": "graugrün behaart; gegenständige ovale Blätter; weiße tief gekerbte Kronblätter; Wiesen",
  "plant-34": "ovale Blätter mit 3 deutlichen Nerven; kleine weiße Sternblüten; schattige Wälder",
  "plant-35": "rosa Blüten mit tief zerschlitzten Kronblättern; gegenständige schmale Blätter; Nasswiesen",
  "plant-36": "aufgeblasener netziger Kelch; weiße gespaltene Blüten; blaugrüne lanzettliche Blätter; trocken",
  "plant-37": "mehlige graugrüne Blätter, obere gänsefußförmig; grüne Knäuelblüten; Ruderalflächen",
  "plant-38": "pfeilförmige saure Blätter mit basalen Lappen; rötliche Rispen; Wiesen",
  "plant-39": "klein, spießförmige Blätter mit abstehenden Grundlappen; rötlich; saure Magerrasen",
  "plant-40": "sehr große stumpfe Grundblätter, wellig; rotbraune Fruchtstände; nährstoffreiche Störstellen",
  "plant-41": "hohle bambusartige Stängel; große dreieckige Blätter mit gerader Basis; dichte Uferbestände",
  "plant-42": "dichter rosa walziger Blütenstand; lange Grundblätter; feuchte Wiesen, Bachufer",
  "plant-43": "gelbe 5er-Blüten, schwarze Drüsen am Rand; Blätter mit Lichtpunkten; Stängel 2-kantig",
  "plant-44": "breite herzförmige Blätter; blassviolette Blüten; heller Sporn; Laubwald",
  "plant-45": "schmalere dreieckige Blätter; langer heller Sporn; trockene saure Wiesen, Heiden",
  "plant-46": "Knoblauchgeruch beim Zerreiben; weiße 4er-Blüten; herz- bis dreieckige Blätter; Säume",
  "plant-47": "blasslila 4er-Blüten; gefiederte Blätter; feuchte Wiesen; oft Schaumnester an Stängeln",
  "plant-48": "Grundrosette; winzige weiße Blüten; dreieckige herzförmige Schötchen; Äcker, Wege",
  "plant-49": "runde flache breit geflügelte Schötchen mit Kerbe; weiß; Äcker, Ruderal",
  "plant-50": "blaugrüne Rosette; weiße Blüten; kleine flache Schötchen; schwermetallreiche Magerrasen",
  "plant-51": "runde Blätter an flachem langem Stiel zittern; glatte graue Borke; Wurzelsprosse",
  "plant-52": "schmale glänzende Blätter; Zweige brechen leicht an Ansatz; Ufer, Auen",
  "plant-53": "breite ovale Blätter, unten graufilzig; große frühe Kätzchen; Waldränder, Hecken",
  "plant-54": "kleine herzförmige Blätter; rostbraune Haarbüschel unten; viele Blüten pro Hochblatt",
  "plant-55": "größere herzförmige Blätter; weiße Haarbüschel unten; wenige Blüten; junge Zweige behaart",
  "plant-56": "milchiger Saft; sehr schmale nadelige Blätter; gelbgrüne Scheinblüten; trockene Rasen",
  "plant-57": "Waldteppiche; gegenständige gesägte Blätter; unscheinbar grüne getrenntgeschlechtliche Blüten",
  "plant-58": "winzige schuppenartige Blätter in 4 Reihen; rosa-violette einseitswendige Blüten; Heide",
  "plant-59": "grüne kantige Zweige; kleine gesägte Blätter; schwarze Beeren; saure Wälder",
  "plant-60": "hoch, gegenständige/quirlige lanzettliche Blätter; gelbe Sternblüten in Rispen; Ufer",
  "plant-61": "runzlige Grundblätter; nickende duftende gelbe Dolden mit orange Flecken; Kalkmagerrasen",
  "plant-62": "cremeweiße schaumige Rispen; unterbrochen gefiederte Blätter; mandeliger Duft; Nasswiesen",
  "plant-63": "gelbe 5er-Blüten; große Endfieder; hakige Fruchtgrannen; Wege, Gebüsch",
  "plant-64": "dreiteilige gesägte Blätter; weiße Blüten; rote Sammelfrucht; Ausläufer; Waldränder",
  "plant-65": "bogige stachelige Triebe; 5-7 Fiederblättchen; rosa-weiße Blüten; rote Hagebutten",
  "plant-66": "bogige dornige Ruten; 5-zählige Blätter; weiße/rosa Blüten; schwarze Sammelfrüchte",
  "plant-67": "aufrechte stachelige Ruten; Blattunterseite weißfilzig; rote Himbeeren; Waldschläge",
  "plant-68": "ovale glänzende Blätter; oft Dornen bei Wildform; weiße Blüten; körnige Birnenfrucht",
  "plant-69": "oval behaarte Blätter; rosa-weiße Blüten; Apfelfrucht mit Kelchresten; Streuobst",
  "plant-70": "unpaarig gefiederte Blätter; weiße Schirmrispen; orange-rote Beeren; Waldränder",
  "plant-71": "Blätter nur flach gelappt; Blüten mit 2-3 Griffeln; Früchte mit 2-3 Steinen",
  "plant-72": "Blätter tief gelappt; Blüten mit 1 Griffel; Früchte mit 1 Stein; Hecken",
  "plant-73": "glänzende Blätter mit 2 roten Drüsen am Stiel; weiße Dolden; rote Kirschen",
  "plant-74": "ovale Blätter; weiße Blüten; blau bereifte Pflaumen/Zwetschgen; Kulturhecken",
  "plant-75": "hängende weiße Trauben; elliptische Blätter; schwarze bittere Beeren; feuchte Wälder",
  "plant-76": "dichter dornenreicher Strauch; weiße Blüten vor Laub; blaue bereifte Schlehen",
  "plant-77": "Blätter riechen stark nach Cassis; schwarze Beeren in Trauben; feuchte Gebüsche",
  "plant-78": "dornenreicher Strauch; kleine gelappte Blätter; grüne/rote oft behaarte Beeren",
  "plant-79": "grüne kantige rutenartige Zweige; wenige kleine Blätter; große gelbe Schmetterlingsblüten",
  "plant-80": "hohe weiße Blütentrauben; 3-zählige gezähnte Blätter; süßer Cumaringeruch; Ruderal",
  "plant-81": "rote kugelige Köpfe; dreiteilige Blätter mit hellem V; behaart; Wiesen",
  "plant-82": "kriechende Ausläufer; weiße Köpfchen; dreiteilige Blätter mit hellem V; Rasen",
  "plant-83": "gelbe Blüten in kleinen Dolden; 5 Blättchen wirkend; Hülsen wie Vogelfuß; Wiesen",
  "plant-84": "gefiederte Blätter; Nebenblattdornen; weiße duftende Trauben; tief gefurchte Borke",
  "plant-85": "viele blauviolette Blüten einseitswendig; zahlreiche schmale Fiederblättchen; Ranken",
  "plant-86": "wenige matte violette Blüten; breitere Fiederblätter; Hecken, Waldränder",
  "plant-87": "gelbe Schmetterlingsblüten; 1 Paar Fiederblätter plus Ranke; kantiger Stängel; Wiesen",
  "plant-88": "spitz gelappte Blätter; Milchsaft im Blattstiel; Flügelnüsse im weiten Winkel",
  "plant-89": "große stumpf gelappte Blätter, unten graugrün; kein Milchsaft; Flügelnüsse spitzwinklig",
  "plant-90": "handförmig 5-7 Fiederblätter; klebrige große Knospen; weiße Blütenkerzen; Stachelkapseln",
  "plant-91": "kleine blassgelbe Blüten mit geradem Sporn; dünne Stängel; Springfrüchte; schattig",
  "plant-92": "sehr hoch; rosa Helmblüten; rote drüsige Knoten; Springfrüchte; feuchte Ufer",
  "plant-93": "3 herzförmige Fiederblättchen; weiße rosa geaderte Blüten; sauer schmeckend; Schatten",
  "plant-94": "rote Stängel; starker Geruch; tief geteilte Blätter; rosa Blüten; geschnäbelte Früchte",
  "plant-95": "hohe schmale Blätter; magenta Blütentrauben; lange Kapseln mit Haarsamen; Kahlschläge",
  "plant-96": "immergrün kletternd; Haftwurzeln; sterile Blätter gelappt, Altersblätter oval; schwarze Beeren",
  "plant-97": "fein fiedrige Blätter; weiße Dolden; hohle gerillte Stängel; Frühjahrswiesen, Säume",
  "plant-98": "dreieckige 3x3-Blätter; weiße Dolden; dichte Rhizomteppiche; Gärten, Auen",
  "plant-99": "fadenfeine aromatische Blätter; weiße Dolden; Bergwiesen, Borstgrasrasen",
  "plant-100": "sehr große raue gelappte Blätter; breite weiße Dolden; behaarter gerillter Stängel",
  "plant-101": "fein zerteilte Blätter; Dolden mit dunkler Mittelblüte; Fruchtstand vogelnestartig",
  "plant-102": "gegenständige Blätter; grüne vierkantige Zweige; rosa Kapseln mit orange Samen",
  "plant-103": "dornenlos; ganze ovale Blätter mit bogenförmigen Nerven; rote dann schwarze Beeren",
  "plant-104": "gelbgrüne gabelige Zweige auf Bäumen; immergrüne ledrige Blätter; weiße Klebbeeren",
  "plant-105": "gegenständige gefiederte Blätter; schwarze Knospen; Büschel einflügeliger Früchte",
  "plant-106": "raue hakige Stängel kleben; Blätter in Quirlen 6-8; kugelige Klettfrüchte",
  "plant-107": "schmale Quirlblätter; lockere weiße Rispen; glatte Stängel; Wiesen, Säume",
  "plant-108": "Quirle aus 6-8 Blättern; weiße Sterne; Waldmeisterduft beim Welken; Buchenwald",
  "plant-109": "markige Triebe; gefiederte Blätter; flache weiße Schirme; schwarze Beeren; starker Geruch",
  "plant-110": "kegelige gelbgrüne Blütenstände; rote Beeren; braunes Mark; Berg- und Schluchtwälder",
  "plant-111": "windend; große weiße Trichterblüten; pfeilförmige Blätter; Hecken, Ufer",
  "plant-112": "blaue Blüten mit gelbem Auge; eingerollte Wickel; feuchte Gräben, Ufer",
  "plant-113": "windender Halbstrauch; violette zurückgeschlagene Kronblätter, gelber Staubkegel; rote Beeren",
  "plant-114": "vierkantiger Stängel; gegenständige gesägte Blätter; braunrote kugelige Blüten; muffiger Geruch",
  "plant-115": "gelblich-weiße Röhrenblüten; schmale Blätter; Halbschmarotzer; lichte saure Wälder",
  "plant-116": "schmale lanzettliche Rippenblätter in Rosette; braune Ähre, weiße Staubfäden-Ringe",
  "plant-117": "breite ovale Rippenblätter in Rosette; grüne lange Ähren; trittfeste Wege",
  "plant-118": "blaue 4-lappige Blüten; 2 Haarleisten am Stängel; gegenständige gezähnte Blätter",
  "plant-119": "hohe einseitswendige purpurne Glocken mit Flecken; wollige Blätter; stark giftig",
  "plant-120": "kriechende Ausläufer; glänzende Blätter; blaue Scheinquirle; Rasen, Waldwege",
  "plant-121": "kriechend aromatisch; rund-nierenförmige gekerbte Blätter; violette Blüten in Achseln",
  "plant-122": "niedrige violette Ähren; dunkle Hochblätter; gegenständige Blätter; Rasen",
  "plant-123": "borstige vierkantige Stängel mit verdickten Knoten; rosa Blüten gelb gezeichnet; Acker",
  "plant-124": "weiße Lippenblüten in Quirlen; nesselartige Blätter ohne Brennhaare; vierkantiger Stängel",
  "plant-125": "gelbe Lippenblüten; oft silbrig gefleckte Blätter; kriechend; schattige Wälder",
  "plant-126": "purpurne Lippenblüten; oft weiß gefleckte Blätter; hohler vierkantiger Stängel; Säume",
  "plant-127": "übel riechend; haarige herzförmige Blätter; dunkelrote Blütenquirle; feuchte Wälder",
  "plant-128": "offene violette Glocken; lockerer verzweigter Wuchs; schmale Blätter; Wiesen",
  "plant-129": "runde Grundblätter, sehr schmale Stängelblätter; nickende blaue Glocken; Magerrasen",
  "plant-130": "gelbe Köpfe vor den Blättern; später hufförmige Blätter unten weißfilzig; Rohboden",
  "plant-131": "riesige rundliche Blätter; rosa Blütenstände vor Laub; nasse Ufer, Gräben",
  "plant-132": "hohe Waldpflanze; viele gelbe Köpfe; lanzettliche gesägte Blätter; Lichtungen",
  "plant-133": "hohe Staude; schmale gesägte Blätter; bogige Rispen voller gelber Köpfe; invasiv",
  "plant-134": "basale Rosette; weiße rosa überlaufene Zungenblüten; gelber Korb; Rasen",
  "plant-135": "fein 2-3fach gefiederte aromatische Blätter; flache weiße/rosa Scheindolden; Wiesen",
  "plant-136": "starker Kamillenduft; hohler kegelförmiger Blütenboden; weiße Zungen später zurückgeschlagen",
  "plant-137": "kein Duft; Blütenboden gefüllt/markig; feine Blätter; Äcker, Ruderal",
  "plant-138": "große Margeritenköpfe; weiße Zungen, gelbe Scheibe; spatelig-lanzettliche Blätter; Wiesen",
  "plant-139": "gelbe Knopfblüten ohne Zungen; stark aromatische fiedrige Blätter; Wege, Brachen",
  "plant-140": "aromatisch; Blätter tief gelappt, unten weißfilzig; kleine graue Körbchen; Ruderal",
  "plant-141": "riesige Blätter; violette Klette-Köpfe mit Haken; zweijährig; nährstoffreiche Ränder",
  "plant-142": "Ausläufer, dichte Bestände; kleine lilane Köpfe; stachelige gelappte Blätter; Äcker",
  "plant-143": "weiche breite Blätter; blassgelbe Köpfe in grünen Hüllblättern; Nasswiesen",
  "plant-144": "schmaler hoher Stängel mit stacheligen Flügeln; dunkle Köpfe; Sümpfe, Nasswiesen",
  "plant-145": "sehr stachelig, herablaufende Blattflügel; große purpurne Köpfe; Ruderal",
  "plant-146": "leuchtend blaue fransige Randblüten; schmale graugrüne Blätter; Äcker",
  "plant-147": "purpurne Köpfe; braune papierig gefranste Hüllblätter; Wiesen",
  "plant-148": "kleine gelbe Löwenzahnköpfe; verzweigt; lyrate Blätter; Waldsäume, Gärten",
  "plant-149": "raue behaarte Grundrosette; fast blattlose verzweigte Schäfte; gelbe Köpfe; Magerwiesen",
  "plant-150": "schmale Grundblätter; gelbe Köpfe im Spätsommer/Herbst; verzweigte schuppige Schäfte",
  "plant-151": "gezähnte Grundrosette; hohler Milchsaft-Schaft; einzelner gelber Kopf; Pusteblume",
  "plant-152": "hohe verzweigte Wiesenpflanze; gelbe Köpfe; Stängelblätter pfeilförmig stängelumfassend",
  "plant-153": "gelbe Köpfe; beblätterter Stängel; behaart; lichte Wälder, Säume; keine Ausläufer",
  "plant-154": "orange-rote Köpfe in Dolden; behaarte Rosette; Ausläufer; magere Wiesen",
  "plant-155": "kleine gelbe Köpfe; graufilzige Rosette; lange Ausläufer; trockene Magerrasen",
  "plant-156": "untergetauchte schmale fädige Blätter; keine Schwimmblätter; kleine Ähren; Stillgewässer",
  "plant-157": "lederige ovale Schwimmblätter; lange Stiele; untergetauchte Phyllodien; Teiche",
  "plant-158": "meist 2 herzförmige Blätter; kleine weiße Sterntraube; rote Beeren; Wald",
  "plant-159": "bogiger Stängel; wechselständige ovale Blätter; hängende weiße Röhren; blau-schwarze Beeren",
  "plant-160": "2 breite Grundblätter; einseitswendige duftende weiße Glocken; rote Beeren; Wälder",
  "plant-161": "schwertförmige Blätter; große gelbe Blüten; dreikantige Kapseln; Röhrichte, Gräben",
  "plant-162": "runde gerillte Stängel; kompakter dunkler Blütenknäuel seitlich; feuchte magere Wiesen",
  "plant-163": "glatte runde markige Stängel; lockere seitliche Blütenrispe; nasse Böden",
  "plant-164": "behaarte grasartige Blattränder; braune Köpfchen; frühe Wiesen, Rasen",
  "plant-165": "weiße sternige lockere Blüten; schmale behaarte Blätter; saure Buchenwälder",
  "plant-166": "dreikantiger Stängel; breite Blätter; große verzweigte Rispe; nasse Waldstellen",
  "plant-167": "hohe Segge; scharf dreikantig; dunkle hängende weibliche Ähren; Ufer, Sümpfe",
  "plant-168": "lange schmale Blätter; lockere hängende Ähren; dichte Teppiche; feuchte Wälder",
  "plant-169": "ovale braune Ährchen dicht gedrängt wie Hasenpfoten; Wiesen",
  "plant-170": "graugrüne Blätter; schwarze weibliche Ähren; feuchte saure Wiesen, Moore",
  "plant-171": "helle weiche Segge; blasse Ähren; weich behaarte Blattscheiden; lichte Wälder, Wiesen",
  "plant-172": "aufgeblasene gelbgrüne Schläuche in dicken hängenden Ähren; nasse Gräben, Röhrichte",
  "plant-173": "glänzende Blattunterseite; Ährchen mit langen Grannen; lockere vielblütige Ähre",
  "plant-174": "Ährchen kantenständig ohne Grannen; glänzende Unterseite; deutliche Öhrchen; Weiden, Rasen",
  "plant-175": "breite überhängende Blätter; lockere Rispe; lange begrannte Ährchen; feuchte Wälder",
  "plant-176": "sehr feine borstliche Blätter in dichten Horsten; kurze Rispe; trockene saure Rasen",
  "plant-177": "breite flache Blätter; offene Rispe; kurze/keine Grannen; fette Wiesen",
  "plant-178": "rote Scheidenbasis; feine und flache Blätter; lockere Rispe; Rasen, Magerrasen",
  "plant-179": "niedrig; bootförmige Blattspitze; runzlige Blattscheide; ganzjährig kleine Rispen",
  "plant-180": "schattig; schmale Blätter stehen waagerecht ab; zarte offene Rispe; Wälder",
  "plant-181": "Rhizome; bootförmige Blattspitze; knieartiger Blattgrund; Wiesen, Rasen",
  "plant-182": "lange spitze Ligula; raue Scheiden; Ausläufer; feuchte nährstoffreiche Wiesen",
  "plant-183": "blaugrüne flache raue Blätter; dichte einseitswendige geknäuelte Rispe; Wiesen",
  "plant-184": "lange Rhizome; breite raue Blätter; Ährchen breitseits paarig an Ähre; Ackerunkraut",
  "plant-185": "sehr hoch; graugrüne raue Blätter; dichte violett-braune Rispe; Brachen, Waldränder",
  "plant-186": "feines Gras; kurze Ligula; locker rötlich-violette Rispe; trockene saure Rasen",
  "plant-187": "kriechende Stolonen; lange Ligula; helle offene Rispe; nasse Wiesen, Ufer",
  "plant-188": "hohes Obergras; lockere Hafer-Rispe; breite Blätter; nährstoffreiche Wiesen",
  "plant-189": "dichte harte Horste; sehr raue Blätter; große luftige Rispe; nasse Wiesen",
  "animal-51": "dunkler; dunkler Schnabel mit orange Band; orange Beine; Zug/Wintergast",
  "animal-52": "weiße Stirnblässe; schwarze Bauchbinden; orange Beine; Wintergans",
  "animal-53": "Männchen grüner Kopf, gelber Schnabel; Weibchen braun; blaues Spiegelfeld",
  "animal-54": "riesiger löffelförmiger Schnabel; Männchen grün/weiß/rostrot; seichtes Wasser",
  "animal-55": "sehr klein; Männchen grüner Augenfleck, gelbes Heckdreieck; schneller Flug",
  "animal-56": "Männchen breiter weißer Überaugenstreif; Sommerente; flache vegetationsreiche Gewässer",
  "animal-57": "Tauchente; Männchen kastanienbrauner Kopf, grauer Körper, schwarze Brust",
  "animal-58": "schwarz-weißes Männchen mit Hängehaube; gelbes Auge; Tauchente",
  "animal-59": "Tauchente; Männchen schwarz-weiß mit rundem weißem Wangenfleck; goldenes Auge",
  "animal-60": "weiß unten; dunkler Augenstreif; geknickte Flügel; fischt im Sturzflug",
  "animal-61": "riesig; breite rechteckige Flügel; weißer Schwanz adult; massiver gelber Schnabel",
  "animal-62": "tief gegabelter rötlicher Schwanz; helle Fenster in Flügeln; eleganter Segler",
  "animal-63": "dunkler, nur schwach gegabelter Schwanz; weniger Kontrast als Rotmilan",
  "animal-64": "niedriger Suchflug über Schilf; lange Flügel; Weibchen cremefarbener Kopf",
  "animal-65": "breite Flügel, kurzer Hals; variable braune Färbung; kreisend, miauender Ruf",
  "animal-66": "klein; kurze breite Flügel, langer Schwanz; Männchen orange gebändert; schnelle Jagd",
  "animal-67": "größer und kräftig; heller Überaugenstreif; gebänderte Unterseite; Waldjäger",
  "animal-68": "rüttelt in der Luft; spitze Flügel; Männchen grauer Kopf/Schwanz; schwarzer Bart",
  "animal-69": "Männchen langer Schwanz, rotes Gesicht, metallischer Kopf; Weibchen braun getarnt",
  "animal-70": "klein grau-braun; orange Gesicht; kastanienbrauner Bauchfleck; Trupps auf Feldern",
  "animal-71": "dunkel; roter Stirnschild, gelbe Schnabelspitze; weiße Flankenlinie",
  "animal-72": "schwarz; weißer Schnabel und Stirnschild; gelappte Zehen; offene Gewässer",
  "animal-73": "heimlich; langer roter Schnabel; graues Gesicht; quiekender Ruf; Röhricht",
  "animal-74": "sehr groß grau; roter Scheitel; schwarz-weißer Kopf; trompetender Zugruf",
  "animal-75": "Schopf; metallisch grün-violett; breite runde Flügel; gaukelnder Flug",
  "animal-76": "sehr langer abwärts gebogener Schnabel; braun gestrichelt; feuchte Wiesen",
  "animal-77": "kleine Möwe; schokobraune Kopfkappe im Sommer; rote Beine/Schnabel; weiße Augenbögen",
  "animal-78": "groß; weiße Halsflecken und weiße Flügelbänder; lautes Flügelklatschen",
  "animal-79": "schlank hellgrau-beige; schwarzer Nackenring; langer Schwanz; Städte, Dörfer",
  "animal-80": "grau gebändert, sperberähnlich; langer Schwanz; Ruf kuckuck; Brutparasit",
  "animal-81": "herzförmiges weißes Gesicht; helle Unterseite; dunkle Augen; Scheunen",
  "animal-82": "riesig; orange Augen; Federohren; tiefer Ruf; Felsen, Wälder",
  "animal-83": "kompakt ohne Federohren; dunkle Augen; Waldkauz-Ruf; Baumhöhlen",
  "animal-84": "lange Federohren; orange Augen; schlank; Winterschlafplätze in Gruppen",
  "animal-85": "einheitlich dunkel; lange Sichelflügel; schrille Rufe; Gebäudebrüter",
  "animal-86": "leuchtend blau-orange; langer Dolchschnabel; pfeilschneller Flug knapp über Wasser",
  "animal-87": "schwarz-weiß-rot; große weiße Schulterfelder; roter Unterschwanz; trommelt",
  "animal-88": "grün; rote Kopfplatte; schwarzer Bartstreif; lachender Ruf; Ameisen am Boden",
  "animal-89": "krähengroß schwarz; Männchen roter Scheitel; große rechteckige Baumhöhlen",
  "animal-90": "lange Schwanzspieße; rostrote Kehle; blauschwarzer Rücken; offene Stallnester",
  "animal-91": "weißer Bürzel; kurzer gegabelter Schwanz; geschlossene Lehmnester außen an Gebäuden",
  "animal-92": "braun gestrichelt; kleine Haube; Singflug über Äckern; weiße Schwanzkanten",
  "animal-93": "schwarz-weiß-grau; langer wippender Schwanz; weiße Gesichtsfelder; Siedlungen/Wasser",
  "animal-94": "grauer Rücken; gelbe Unterseite; sehr langer Schwanz; Bäche, Gebirgsbäche",
  "animal-95": "winzig braun; kurzer aufgestellter Schwanz; sehr lauter Gesang; Gebüsch",
  "animal-96": "braun mit weißer Brust; knickst auf Steinen; taucht in schnell fließenden Bächen",
  "animal-97": "orange Gesicht und Brust; brauner Rücken; große dunkle Augen; aufrechte Haltung",
  "animal-98": "dunkelgrau bis schwarz; rostrot zitternder Schwanz; Hausdächer, Felsen",
  "animal-99": "Männchen orange Brust, schwarze Kehle, weiße Stirn; rostiger Schwanz; Obstgärten",
  "animal-100": "Männchen schwarz mit gelbem Schnabel; Weibchen braun; melodischer Gesang",
  "animal-101": "warmbraun; helle Brust mit tropfenförmigen Flecken; wiederholt Gesangsphrasen",
  "animal-102": "grauer Kopf und Bürzel, kastanienbrauner Rücken; gefleckte Brust; Trupps",
  "animal-103": "grau; Männchen schwarze Kappe, Weibchen braune; flötender Gesang; Gebüsch",
  "animal-104": "klein oliv; dunkle Beine; kurzer Flügel; monotoner zilp-zalp-Ruf",
  "animal-105": "klein oliv; helle Beine; längerer Flügel; abfallender weicher Gesang",
  "animal-106": "winzig; orange Scheitel, deutlicher weißer Überaugenstreif, schwarzer Augenstreif",
  "animal-107": "winzig; gelb/orange Scheitel, schlichtes Gesicht; hohe Rufe; Nadelwald",
  "animal-108": "schwarzer Kopf, weiße Wangen und weißer Nackenfleck; 2 Flügelbinden; Fichten",
  "animal-109": "spitze Haube; schwarz-weißes Gesichtsmuster; braun-grau; Nadelwald",
  "animal-110": "blauer Scheitel/Flügel; gelber Bauch; schwarzer Augenstreif; klein",
  "animal-111": "schwarzer Kopf, weiße Wangen; gelber Bauch mit schwarzem Längsstreifen; groß",
  "animal-112": "klettert kopfüber; blau-grau oben, orange Flanken; schwarzer Augenstreif",
  "animal-113": "rosa-braun; blau-schwarzes Flügelfeld; weißer Bürzel; rauer Warnruf",
  "animal-114": "Rabenkrähe schwarz, Nebelkrähe grau-schwarz; schwerer Schnabel; Paare/Trupps",
  "animal-115": "Rabenkrähe schwarz, Nebelkrähe grau-schwarz; schwerer Schnabel; Paare/Trupps",
  "animal-116": "sehr groß; keilförmiger Schwanz; zottige Kehle; tiefer kroak-Ruf",
  "animal-117": "klein; grauer Nacken; helle Augen; Kolonien an Gebäuden/Felsen",
  "animal-118": "nackte helle Schnabelbasis adult; schwarze Koloniekrähe; Felder",
  "animal-119": "schwarz-weiß; sehr langer Schwanz; metallischer Glanz; chackernde Rufe",
  "animal-120": "glänzend dunkel mit hellen Sprenkeln; kurzer Schwanz; spitze Flügel; Schwärme",
  "animal-121": "Männchen grauer Scheitel, schwarze Kehle, kastanienbrauner Nacken; Gebäudenähe",
  "animal-122": "kastanienbrauner Scheitel; schwarzer Wangenfleck; weißer Halsring; ländlich",
  "animal-123": "grün-gelb; kräftiger heller Schnabel; gelbe Flügel- und Schwanzkanten",
  "animal-124": "rotes Gesicht; schwarz-weißer Kopf; gelbe Flügelbinde; Disteln",
  "animal-125": "klein grün-gelb; Männchen schwarzer Scheitel; gelbe Flügelbinden; Erlen",
  "animal-126": "massiger heller Kegelschnabel; großer Kopf; orangebraun; weiße Flügelbinden",
  "animal-127": "Männchen rosa Brust, blaugrauer Kopf; 2 weiße Flügelbinden; Buchfinkenschlag",
  "animal-128": "plump; schwarzer Scheitel; weißer Bürzel; Männchen rote, Weibchen graue Unterseite",
  "animal-129": "gelber Kopf/Brust, braun gestrichelt; Gesang zi-zi-zi-zieh; Hecken, Felder",
  "animal-130": "Maulwurfshügel; schwarze Samtbehaarung; riesige Grabfüße; Gänge",
  "animal-131": "braune Stacheln; spitzes Gesicht; kurze Beine; Gärten, Hecken",
  "animal-132": "lange schwarzspitzige Ohren; lange Hinterläufe; bernsteinfarbene Augen; offene Felder",
  "animal-133": "kürzere Ohren/Beine als Hase; weißer Schwanz; gräbt Baue; Kolonien",
  "animal-134": "groß bunt; schwarzer Bauch, weiße Backenflecken; Ackerbaue, Vorratskammern",
  "animal-135": "rotbraun bis dunkel; buschiger Schwanz; Winter-Ohrpinsel; Kobel in Bäumen",
  "animal-136": "platte beschuppte Kelle; orange Schneidezähne; Dämme/Baue; angenagte Stämme",
  "animal-137": "grau, weißer Bauch; große Augen; buschiger Schwanz; Dachböden, Buchenwälder",
  "animal-138": "weißer Kehlfleck gabelt zu Vorderbeinen; helle Nase; Häuser, Scheunen",
  "animal-139": "gelber Kehlfleck meist rund, nicht gegabelt; dunkle Nase; Waldmarder",
  "animal-140": "dunkelbraun mit heller Gesichtsmaske; starker Moschusgeruch; Gewässerränder",
  "animal-141": "braun/weiß; längerer Schwanz mit schwarzer Spitze; im Winter oft weiß",
  "animal-142": "sehr klein; kurzer Schwanz ohne schwarze Spitze; braun oben, weiß unten",
  "animal-143": "massig; schwarz-weiß gestreifter Kopf; breite Grabfüße; Erdbau",
  "animal-144": "rotbraun; weiße Schwanzspitze; schwarze Beine/Ohren; spitze Schnauze",
  "animal-145": "stromlinienförmig; Schwimmhäute; dicker Schwanz; Kotspuren an Ufern",
  "animal-146": "borstig dunkel; langer Rüssel; Hauer; Frischlinge gestreift; Wühlspuren",
  "animal-147": "groß; Männchen stark verzweigtes Geweih; heller Spiegel; Röhren in Brunft",
  "animal-148": "oft gefleckt; Männchen schaufelförmiges Geweih; langer schwarzer Schwanzstreif",
  "animal-149": "klein; weißer Spiegel; kurzes Geweih; kein sichtbarer Schwanz; bellt",
  "animal-150": "Wildschaf; Männchen große Schneckenhörner; heller Sattelfleck; felsige Hänge",
  "taxon-1": "unsegmentiert rundlich; Pseudocoel; Cuticula; vollständiger Darm",
  "taxon-2": "weicher Körper; Mantel, oft Schale; muskulöser Fuß; Radula außer Muscheln",
  "taxon-3": "segmentierte Würmer; Borsten oft vorhanden; echtes Coelom; geschlossener Blutkreislauf",
  "taxon-4": "Chitinpanzer; gegliederte Beine; segmentierter Körper; Häutung",
  "taxon-5": "Rückensaite, dorsales Nervenrohr, Kiemenspalten zumindest im Embryo",
  "taxon-6": "2 Antennenpaare; Kiemen; oft aquatisch; harter Panzer",
  "taxon-7": "Tracheenatmung; 1 Antennenpaar; Landarthropoden: Tausendfüßer, Insekten",
  "taxon-9": "freilebende Plattwürmer; bewimperte Unterseite; Augenflecken; gleiten auf Steinen/Pflanzen",
  "taxon-10": "mikroskopisch; Räderorgan/Kranzwimpern; Mastax-Kiefer; Süßwasser, Aufwuchs",
  "taxon-11": "2 Schalenklappen mit Schloss; kein Kopf, keine Radula; Filterer mit Kiemen",
  "taxon-12": "Kriechfuß, Kopf mit Fühlern; meist spiralige Schale; Radula; Land/Wasser",
  "taxon-13": "4 Beinpaare; keine Antennen; Cheliceren; Kopfbrust plus Hinterleib",
  "taxon-14": "blattförmige Beine; Süßwasser; oft Carapax; Daphnien/Feenkrebse",
  "taxon-15": "höhere Krebse; 5 Kopf-, 8 Brust-, 6 Hinterleibssegmente; Scheren oft",
  "taxon-16": "viele Rumpfsegmente und Beine; Kopf mit Antennen; landlebend",
  "taxon-17": "Kopf, Brust, Hinterleib; 3 Beinpaare; Antennen; meist Flügel",
  "taxon-18": "aquatisch; Kiemen, Flossen, Schuppen meist; wechselwarm",
  "taxon-19": "feuchte Haut; Laich ohne Schale im Wasser; Larven mit Kiemen; Metamorphose",
  "taxon-20": "trockene Hornschuppen; Lungen; Amnioteneier; wechselwarm",
  "taxon-21": "Federn; Schnabel; Flügel; hartschalige Eier; gleichwarm",
  "taxon-22": "Haare; Milchdrüsen; gleichwarm; 3 Gehörknöchelchen; meist lebendgebärend",
  "taxon-23": "1 Beinpaar pro Segment; flach; Giftklauen; schnelle Räuber",
  "taxon-24": "2 Beinpaare pro Doppelsegment; rundlich; langsam; rollen sich oft ein",
  "taxon-25": "kräftige Libellen; Hinterflügel breiter; Flügel in Ruhe ausgebreitet; Augen berühren sich oft",
  "taxon-26": "schlank; Flügel gleich schmal, in Ruhe meist zusammengelegt; Augen weit getrennt",
  "taxon-27": "seitlich zusammengedrückt; Flohkrebsform; kein Carapax; springend/seitlich schwimmend",
  "taxon-28": "dorsoventral flach; 7 Beinpaare; Asseln; Land und Wasser",
  "taxon-29": "Süßwasser-Lungenschnecken; Augen an Fühlerbasis; dünne Schale, kein Deckel",
  "taxon-30": "Landschnecken; Augen an Fühlerspitzen; 2 Fühlerpaare; Lungenatmung",
  "taxon-31": "wenige Borsten; keine Parapodien; Clitellum; Boden und Süßwasser",
  "taxon-32": "abgeflacht segmentiert; Saugnapf vorn und hinten; keine Borsten; Wasser/feucht",
  "taxon-33": "Körper einteilig oval; sehr lange Beine; kein Spinnenfaden, kein Gift; Augenhügel",
  "taxon-34": "2 Körperabschnitte mit schmaler Taille; Giftklauen; Spinnwarzen",
  "taxon-35": "Milben/Zecken; Körper verschmolzen; Larven 6 Beine, Adulte 8; sehr klein",
  "taxon-36": "Wasserlarven; Adult kurzlebig; 2-3 Schwanzfäden; Flügel aufrecht",
  "taxon-37": "räuberische Wasserlarven; Adult mit großen Augen, 2 Flügelpaaren, nicht faltbar",
  "taxon-38": "lange Fühler; Sprungbeine; schwert-/säbelförmiger Legebohrer; Grillen, Laubheuschrecken",
  "taxon-39": "kurze Fühler; Sprungbeine; Trommelfell am Hinterleib; kurze Legeröhre",
  "taxon-40": "Zangen am Hinterende; kurze Lederflügel; nachtaktiv; abgeflacht",
  "taxon-41": "Stechrüssel; Halbdecken mit harter Basis, häutiger Spitze; Duftdrüsen",
  "taxon-42": "Zikaden; Sprungbeine; dachförmige Flügel; Saugrüssel hinten am Kopf",
  "taxon-43": "weiche birnförmige Kolonien; Siphonen am Hinterleib; Honigtau",
  "taxon-44": "winzige springende Pflanzensauger; dachförmige Flügel; Larven oft wachsig",
  "taxon-45": "schnabelartig verlängerter Kopf; klare gefleckte Flügel; Männchen oft Skorpionende",
  "taxon-46": "netzartig geaderte Flügel; räuberische Larven mit Sicheln; Florfliegen, Ameisenlöwen",
  "taxon-47": "1 Flügelpaar plus Halteren; große Augen; Larven oft Maden",
  "taxon-48": "harte Deckflügel; kauende Mundwerkzeuge; vollständige Metamorphose",
  "taxon-49": "haarige dachförmige Flügel; Wasserlarven bauen Köcher oder Netze",
  "taxon-50": "2 Flügelpaare mit Häkchen gekoppelt; Wespentaille oft; Legestachel/Stachel",
  "taxon-51": "Schuppenflügel; Rollrüssel; Raupen mit Bauchfüßen; Tag- und Nachtfalter",
  "taxon-52": "Tauchvögel; gelappte Zehen; Beine weit hinten; schlechte Läufer",
  "taxon-53": "Fischfresser; alle 4 Zehen schwimmhäutig; lange Hälse; kolonial oft",
  "taxon-54": "langbeinige Watvögel; langer Hals und Schnabel; langsam fliegend",
  "taxon-55": "Schwimmhäute; breiter lamellierter Schnabel; wassergebunden",
  "taxon-56": "Greifvögel mit Hakenschnabel, Fängen; breite Flügel; Tagjäger",
  "taxon-57": "Bodenbewohner; kräftige Beine; kurze runde Flügel; Küken Nestflüchter",
  "taxon-58": "Kraniche und Rallen; lange Beine oder Schilfbewohner; kräftige Zehen",
  "taxon-59": "Watvögel, Möwen, Alken; Gewässerränder; meist lange Flügel",
  "taxon-60": "plumpe Körnerfresser; kleiner Kopf; schneller Flug; Kropfmilch",
  "taxon-61": "Kuckucke; zygodactyle Füße; langer Schwanz; Brutparasit typisch",
  "taxon-62": "Gesichtsschleier; große Augen; lautloser Flug; Fänge; meist nachtaktiv",
  "taxon-63": "Segler; sichelförmige Flügel; winzige Füße; Dauerflug in der Luft",
  "taxon-64": "bunte Ansitzjäger mit kräftigem Schnabel; kurze Beine; Höhlenbrüter oft",
  "taxon-65": "Kletterfüße 2 vorn/2 hinten; Stützschwanz; Meißelschnabel; trommeln",
  "taxon-66": "Sitzfuß 3 vorn/1 hinten; Gesangsapparat; größte Vogelordnung",
  "taxon-67": "kleine Insektenfresser; spitze Schnauze; scharfe Zähne; oft nachtaktiv",
  "taxon-68": "Flughaut zwischen verlängerten Fingern; Echoortung; nachtaktive Insektenjäger",
  "taxon-69": "2 obere Schneidezahnpaare; lange Ohren; Pflanzenfresser; keine Nagetiere",
  "taxon-70": "je 1 Schneidezahnpaar oben/unten; Diastema; Nagezähne wachsen ständig",
  "taxon-71": "Eckzähne und Reißzähne; Krallen; Fleischfressergebiss, oft Allesfresser",
  "taxon-72": "Paarhufer; Gewicht auf 3./4. Zeh; Klauen; Pflanzenfresser",
  "taxon-73": "Schlammschnecken; rechtsgewundene hohe Schale; breite Fußsohle; dreieckige Fühler",
  "taxon-74": "dünne bernsteinfarbene durchscheinende Schale; feuchte Uferpflanzen",
  "taxon-75": "runde spiralige Landschnecken-Schalen; 2 Fühlerpaare; Kalkgebiete, Gärten",
  "taxon-76": "Nacktschnecken ohne Außenschale; Atemloch vor Mantelmitte; viel Schleim; kein Kiel",
  "taxon-77": "zylindrisch segmentiert; Clitellum; Borstenreihen; Erdgänge, Kotkrümel",
  "taxon-78": "räuberische Egel ohne Kiefer; nicht blutsaugend; Süßwasser, unter Steinen",
  "taxon-79": "Radnetz; oft kugeliger Hinterleib; auffällige Zeichnung; Gärten, Wiesen",
  "taxon-80": "kompakt; riesige Frontaugen; Sprungjagd; keine Fangnetze",
  "taxon-81": "Bodenjäger; Augen in 3 Reihen; Weibchen trägt Eikokon/Junge",
  "taxon-82": "schildförmig; großes Schildchen; kräftiger Körper; Stinkdrüsen",
  "taxon-83": "weich, schlank; Keilfeld/Cuneus im Vorderflügel; viele Pflanzenwanzen",
  "taxon-84": "laufstark; lange Beine; räuberisch; längsgerillte Deckflügel; Bodenbewohner",
  "taxon-85": "rund gewölbt; oft rot-gelb mit Punkten; kurze Keulenfühler; Blattlausjäger",
  "taxon-86": "lamellenförmige Fühlerkeule; kräftig oval; grabende Beine; Dung-, Mai-, Rosenkäfer",
  "taxon-87": "Männchen oft mit großen Mandibeln; lamellierte Fühler; Larven in Totholz",
  "taxon-88": "sehr lange Fühler; länglicher Körper; Larven bohren in Holz/Pflanzenstängeln",
  "taxon-89": "oval, oft bunt/metallisch; Pflanzenfresser; kurze Fühler; Blattfraß",
  "taxon-90": "Rüsselkopf; gekniete Fühler am Rüssel; kompakt; Larven in Pflanzen",
  "taxon-91": "Schnappmechanismus; spitze Hinterecken am Halsschild; Drahtwurmlarven",
  "taxon-92": "sehr kurze Deckflügel; freier beweglicher Hinterleib; schnelle Räuber/Aasfresser",
  "taxon-93": "gekniete Fühler; 1-2 Stielchenglieder; Staaten mit Arbeiterinnen",
  "taxon-94": "behaart, Pollensammelhaare/-körbchen; lange Zunge oft; Bestäuber",
  "taxon-95": "klein robust; Haken an Fühlerkolben; schneller hüpfender Flug; Flügel halb offen",
  "taxon-96": "metallisch dunkel, oft rote Flecken; keulige Fühler; tagaktiv langsam; Warnfarben",
  "taxon-97": "vordere Beinpaare verkürzt bürstenartig; farbige Flügel, oft Augenflecken",
  "taxon-98": "große Tagfalter; oft Schwänze; Raupen mit Osmeterium; 6 Laufbeine",
  "taxon-99": "kleine Bläulinge/Kupferfalter; Unterseiten gepunktet; oft Ameisenbezug",
  "taxon-100": "weiß/gelb/orange; schwarze Spitzen/Flecken; Raupen oft Kreuzblütler",
  "taxon-101": "kräftige Nachtfalter; Tarn-Vorderflügel; Hinterflügel schlichter; Raupen oft Erdraupen",
  "taxon-102": "breite flache Flügel; Tarnmuster; Raupen als Spanner mit wenigen Bauchfüßen",
  "taxon-103": "stromlinienförmig; schmale Flügel; Schwirrflug; Raupen oft mit Horn",
  "taxon-104": "spitze lange Schnauze; winzige Augen; oft rote Zahnspitzen; moschusartig",
  "taxon-105": "walzenförmig; Schaufelvorderfüße; winzige Augen; Samtfell; unterirdisch",
  "taxon-106": "Stachelkleid; rollt sich ein; nachtaktiv; Insekten/Schnecken",
  "taxon-107": "lange Schwänze; spitze Schnauze; große Ohren; Mäuse/Ratten, meist Allesfresser",
  "taxon-108": "kräftig; Backentaschen bei Hamstern; kurze Schwänze; Vorratssammler",
  "taxon-109": "stumpfe Schnauze; kleine Ohren; kurzer Schwanz; Wühlmäuse, Pflanzenfresser",
  "taxon-110": "buschiger Schwanz; gute Kletterer/Springer; tagaktiv; Nüsse/Samen",
  "taxon-111": "sehr große Nager; flacher Schwanz; Schwimmhäute; Baumfäller",
  "taxon-112": "nachtaktive Kletterer; große Augen; buschiger Schwanz; langer Winterschlaf",
  "taxon-0": "dorsoventral flach; kein Coelom; blind endender Darm oft verzweigt; freie Formen bewimpert",
  "taxon-8": "Wirbelsäule und Schädel; inneres Skelett; paarige Sinnesorgane"
};
