Object.assign(FEATURES, {
  "plant-189": "dichte harte Horste; sehr raue Blätter; große luftige Rispe; nasse Wiesen",
  "plant-190": "fadenfeine eingerollte Blätter; lockere geschlängelte Rispe; saure Wälder, Heiden",
  "plant-191": "weich samtig behaart; graugrün; rosa überlaufene Rispe; Wiesen",
  "plant-192": "kriechende Rhizome; Haare v.a. an Knoten; weiche Blätter; lichte Wälder",
  "plant-193": "breite weiche Blätter; große überhängende lockere Rispe; schattige Laubwälder",
  "plant-194": "dichte zylindrische Scheinähre; kurze Grannen; oft zwiebeliger Grund; Wiesen",
  "plant-195": "weiche zylindrische Fuchsschwanzähre; früh blühend; feuchte Wiesen",
  "plant-196": "schilfartig hoch; breite Blätter; dichte Rispe; Ufer, Gräben, Röhrichte",
  "plant-197": "süßer Cumaringeruch beim Trocknen; frühe gelbgrüne Ährenrispe; Wiesen",
  "plant-198": "sehr hohes Röhricht; hohle Halme; breite Blätter; große braunviolette Feder-Rispe",
  "plant-199": "winzige ovale Schwimmblättchen, je 1 Wurzel; dichte Matten auf Stillwasser",
  "plant-200": "schmale Blätter; männliche und weibliche Kolben durch Lücke getrennt; schlanker Kolben",
  "plant-201": "breite Blätter; männlicher und weiblicher Kolben berühren sich; dicker brauner Kolben",
  "animal-0": "orange-schwarz; weiße Flügelspitzen; kleine Augenflecken hinten; Disteln, Wanderfalter",
  "animal-1": "schwarz mit roten Bändern und weißen Vorderflügelspitzen; kräftiger Wanderfalter",
  "animal-2": "orange mit schwarzen/gelben Flecken und blauem Rand; Raupen an Brennnessel",
  "animal-3": "gezackte Flügel; orangebraun; weißes C auf Unterseite; überwintert",
  "animal-4": "groß dunkel weinbraun; gelber Rand und blaue Flecken; Weiden, Birken",
  "animal-5": "rotbraun; 4 große Augenflecken; Raupen an Brennnessel",
  "animal-6": "Frühjahr orange, Sommer schwarz-weiß; Unterseite netzartig wie Landkarte",
  "animal-7": "gelb-schwarz, Schwanzzipfel, roter Augenfleck; Raupen an Doldenblütlern",
  "animal-8": "blattförmige spitze Flügel; Männchen zitronengelb, Weibchen blass; überwintert",
  "animal-9": "Männchen orange Vorderflügelspitzen; Unterseite grün marmoriert; Wiesenschaumkraut",
  "animal-10": "Unterseite grünlich geaderte Adern; kleiner Weißling; feuchte Wiesen, Hecken",
  "animal-11": "klein; schwacher schwarzer Spitzenfleck; 1-2 schwarze Vorderflügelpunkte",
  "animal-12": "groß; starke schwarze Flügelspitzen; Weibchen mit 2 schwarzen Punkten; Kohl",
  "animal-13": "Kolibriartiger Schwirrflug am Tag; langer Rüssel; orange Hinterflügel",
  "animal-14": "schlangenförmig; keine Bauchflossen; winzige Schuppen; nachtaktiv, Wanderfisch",
  "animal-15": "Entenschnabel; Rückenflosse weit hinten; lang torpedoförmig; Lauerjäger",
  "animal-16": "hoch gebaut; lange Rückenflosse; Barteln am Maul; große Schuppen",
  "animal-17": "Forelle mit Fettflosse; rote und schwarze Punkte; kalte sauerstoffreiche Bäche",
  "animal-18": "rosa Regenbogenband; schwarze Punkte auch auf Schwanz; Fettflosse; oft Besatzfisch",
  "animal-19": "3 freie Rückenstacheln; Knochenplatten; Männchen rot zur Brutzeit; Nestbauer",
  "animal-20": "silbrig; rote Iris und Flossen; endständiges Maul; Schwarmfisch",
  "animal-21": "olivgrün, sehr schleimig; winzige Schuppen; abgerundete Flossen; kleine Barteln",
  "animal-22": "bronze, hochrückig; keine Barteln; lange Rückenflosse; schlammige Stillgewässer",
  "animal-23": "sehr klein; oberständiges Maul; silbriger Seitenstreif; Schwärme an Oberfläche",
  "animal-24": "grundnah; je 1 Bartel am Maulwinkel; dunkle Seitenflecken; Kiesgrund",
  "animal-25": "klein; dunkles Seitenband; Männchen zur Laichzeit rötlich; kühle klare Bäche",
  "animal-26": "warzig braun; kupferne Augen; große Ohrdrüsen; läuft; Laichschnüre",
  "animal-27": "klein warzig; herzförmige Pupille; orange-roter Bauch; flache warme Tümpel",
  "animal-28": "hellgrün; Haftscheiben an Zehen; dunkler Seitenstreif; klettert in Sträuchern",
  "animal-29": "braun; dunkle Schläfenmaske; stumpfe Schnauze; Laichballen; feuchte Wälder/Wiesen",
  "animal-30": "grüner Wasserfrosch-Komplex; oft heller Rückenstreif; bleibt stark ans Wasser gebunden",
  "animal-31": "groß; warzige dunkle Oberseite; orange Bauch; Männchen hoher gezackter Kamm",
  "animal-32": "Männchen blau-grau; Bauch kräftig orange ohne Flecken; Berg- und Waldtümpel",
  "animal-33": "klein; Bauch gefleckt; Männchen welliger Kamm; häufige Gartenteiche",
  "animal-34": "beinlose Echse; glatte glänzende Schuppen; bewegliche Lider; Schwanz bricht leicht",
  "animal-35": "gelber/weißer Halsring; gekielte Schuppen; runde Pupille; schwimmt, frisst Amphibien",
  "animal-36": "glatte Schuppen; dunkler Augenstreif; runde Pupille; kein Halsring; trockene Hänge",
  "animal-37": "dunkles Zickzackband; senkrechte Pupille; dreieckiger Kopf; giftig; Moore/Heiden",
  "animal-38": "kleine braune Echse; dunkle Seiten; lebendgebärend; kühle feuchte Habitate",
  "animal-39": "kräftig; Augenflecken an Flanken; Männchen grüne Seiten; sandige trockene Stellen",
  "animal-40": "groß; langer Hals; schwarze Federohren und kastanienbraune Halskrause im Prachtkleid",
  "animal-41": "sehr klein; kurzer Schnabel; kastanienbrauner Hals im Prachtkleid; versteckte Teiche",
  "animal-42": "schwarz; langer Hals, Hakenschnabel; taucht; trocknet Flügel ausgebreitet",
  "animal-43": "groß grau; schwarzer Augenstreif; Hals im Flug S-förmig eingezogen",
  "animal-44": "sehr großer weißer Reiher; gelber Schnabel außerhalb Brutzeit; schwarze Beine",
  "animal-45": "braun gestreift; dicker Hals; Tarnhaltung im Schilf; dumpfes Boom",
  "animal-46": "weiß mit schwarzen Schwungfedern; roter Schnabel und Beine; Horste auf Gebäuden",
  "animal-47": "dunkel metallisch oben, weißer Bauch; roter Schnabel/Beine; Waldgewässer",
  "animal-48": "orange Schnabel mit schwarzem Höcker; S-Hals; oft Flügel leicht aufgestellt",
  "animal-49": "gelber keilförmiger Schnabel; gerader Hals; laute trompetende Rufe",
  "animal-50": "große graue Gans; heller Vorderflügel; orange/rosa Schnabel; Stammmutter Hausgans"
});
