// [latin, german, latin aliases, german aliases]
const PLANTS = [
  ["Equisetum arvense", "Acker-Schachtelhalm"],
  ["Equisetum sylvaticum", "Wald-Schachtelhalm"],
  ["Pteridium aquilinum", "Adlerfarn"],
  ["Athyrium filix-femina", "Wald-Frauenfarn"],
  ["Dryopteris carthusiana", "Dorniger Wurmfarn", "", "Gewöhnlicher Dornfarn"],
  ["Dryopteris dilatata", "Breitblättriger Wurmfarn", "", "Breitblättriger Dornfarn"],
  ["Dryopteris filix-mas", "Gewöhnlicher Wurmfarn"],
  ["Abies alba", "Weiß-Tanne"],
  ["Pseudotsuga menziesii", "Douglasie"],
  ["Picea abies", "Gemeine Fichte"],
  ["Larix decidua", "Europäische Lärche"],
  ["Pinus sylvestris", "Wald-Kiefer", "", "Föhre"],
  ["Nuphar lutea", "Teichrose"],
  ["Nymphaea alba", "Weiße Seerose"],
  ["Anemone nemorosa", "Busch-Windröschen"],
  ["Caltha palustris", "Sumpf-Dotterblume"],
  ["Ficaria verna", "Scharbockskraut"],
  ["Ranunculus acris", "Scharfer Hahnenfuß"],
  ["Ranunculus repens", "Kriechender Hahnenfuß"],
  ["Chelidonium majus", "Schöllkraut"],
  ["Papaver rhoeas", "Klatsch-Mohn"],
  ["Fagus sylvatica", "Rotbuche"],
  ["Quercus petraea", "Trauben-Eiche"],
  ["Quercus robur", "Stiel-Eiche"],
  ["Quercus rubra", "Rot-Eiche"],
  ["Betula pendula", "Hänge-Birke"],
  ["Alnus glutinosa", "Schwarz-Erle"],
  ["Carpinus betulus", "Hainbuche"],
  ["Corylus avellana", "Hasel"],
  ["Ulmus glabra", "Berg-Ulme"],
  ["Urtica dioica", "Große Brennnessel"],
  ["Stellaria graminea", "Gras-Sternmiere"],
  ["Stellaria media agg.", "Vogel-Sternmiere", "Stellaria media", "Vogelmiere"],
  ["Cerastium holosteoides", "Gewöhnliches Hornkraut", "Cerastium fontanum"],
  ["Moehringia trinervia", "Dreinervige Nabelmiere"],
  ["Lychnis flos-cuculi", "Kuckucks-Lichtnelke"],
  ["Silene vulgaris", "Taubenkropf-Leimkraut"],
  ["Chenopodium album agg.", "Weißer Gänsefuß", "Chenopodium album"],
  ["Rumex acetosa", "Wiesen-Sauerampfer"],
  ["Rumex acetosella", "Kleiner Sauerampfer"],
  ["Rumex obtusifolius", "Stumpfblättriger Ampfer"],
  ["Fallopia japonica", "Japanischer Staudenknöterich", "Reynoutria japonica"],
  ["Bistorta officinalis", "Schlangen-Wiesenknöterich", "Polygonum bistorta"],
  ["Hypericum perforatum", "Tüpfel-Johanniskraut", "", "Tüpfel-Hartheu"],
  ["Viola riviniana", "Hain-Veilchen"],
  ["Viola canina", "Hunds-Veilchen"],
  ["Alliaria petiolata", "Knoblauchsrauke"],
  ["Cardamine pratensis agg.", "Wiesen-Schaumkraut", "Cardamine pratensis"],
  ["Capsella bursa-pastoris", "Gewöhnliches Hirtentäschel"],
  ["Thlaspi arvense", "Acker-Hellerkraut"],
  ["Noccaea caerulescens", "Gebirgs-Hellerkraut", "Noccea caerulescens"],
  ["Populus tremula", "Zitter-Pappel"],
  ["Salix fragilis", "Bruch-Weide"],
  ["Salix caprea", "Sal-Weide"],
  ["Tilia cordata", "Winter-Linde"],
  ["Tilia platyphyllos", "Sommer-Linde"],
  ["Euphorbia cyparissias", "Zypressen-Wolfsmilch"],
  ["Mercurialis perennis", "Wald-Bingelkraut"],
  ["Calluna vulgaris", "Heidekraut", "", "Besenheide"],
  ["Vaccinium myrtillus", "Heidelbeere", "", "Blaubeere"],
  ["Lysimachia vulgaris", "Gewöhnlicher Gilbweiderich"],
  ["Primula veris", "Wiesen-Schlüsselblume"],
  ["Filipendula ulmaria", "Echtes Mädesüß"],
  ["Geum urbanum", "Echte Nelkenwurz"],
  ["Fragaria vesca", "Wald-Erdbeere"],
  ["Rosa canina agg.", "Hunds-Rose", "Rosa canina"],
  ["Rubus fruticosus agg.", "Echte Brombeere", "Rubus fruticosus"],
  ["Rubus idaeus", "Himbeere"],
  ["Pyrus communis", "Kultur-Birne", "Pyrus pyraster", "Wild-Birne"],
  ["Malus communis", "Kultur-Apfel", "Malus sylvestris", "Wild-Apfel"],
  ["Sorbus aucuparia", "Vogelbeere", "", "Eberesche"],
  ["Crataegus laevigata agg.", "Zweigriffliger Weißdorn", "Crataegus laevigata"],
  ["Crataegus monogyna", "Eingriffliger Weißdorn"],
  ["Prunus avium", "Vogel-Kirsche", "", "Süß-Kirsche"],
  ["Prunus domestica", "Pflaume", "", "Zwetschge"],
  ["Prunus padus", "Gewöhnliche Traubenkirsche"],
  ["Prunus spinosa", "Schlehe", "", "Schwarzdorn"],
  ["Ribes nigrum", "Schwarze Johannisbeere"],
  ["Ribes uva-crispa", "Stachelbeere"],
  ["Cytisus scoparius", "Besen-Ginster"],
  ["Melilotus alba", "Weißer Steinklee"],
  ["Trifolium pratense", "Rot-Klee", "", "Wiesen-Klee"],
  ["Trifolium repens", "Weiß-Klee"],
  ["Lotus corniculatus", "Gewöhnlicher Hornklee"],
  ["Robinia pseudoacacia", "Robinie"],
  ["Vicia cracca", "Vogel-Wicke"],
  ["Vicia sepium", "Zaun-Wicke"],
  ["Lathyrus pratensis", "Wiesen-Platterbse"],
  ["Acer platanoides", "Spitz-Ahorn"],
  ["Acer pseudoplatanus", "Berg-Ahorn"],
  ["Aesculus hippocastanum", "Rosskastanie"],
  ["Impatiens parviflora", "Kleinblütiges Springkraut"],
  ["Impatiens glandulifera", "Drüsiges Springkraut"],
  ["Oxalis acetosella", "Wald-Sauerklee"],
  ["Geranium robertianum", "Stinkender Storchschnabel"],
  ["Epilobium angustifolium", "Schmalblättriges Weidenröschen"],
  ["Hedera helix", "Efeu"],
  ["Anthriscus sylvestris", "Wiesen-Kerbel"],
  ["Aegopodium podagraria", "Geißfuß", "", "Giersch"],
  ["Meum athamanticum", "Bärwurz"],
  ["Heracleum sphondylium", "Wiesen-Bärenklau"],
  ["Daucus carota", "Wilde Möhre"],
  ["Euonymus europaea", "Europäisches Pfaffenhütchen"],
  ["Frangula alnus", "Faulbaum"],
  ["Viscum album", "Laubholz-Mistel"],
  ["Fraxinus excelsior", "Gewöhnliche Esche"],
  ["Galium aparine", "Kletten-Labkraut"],
  ["Galium album", "Wiesen-Labkraut"],
  ["Galium odoratum", "Waldmeister"],
  ["Sambucus nigra", "Schwarzer Holunder"],
  ["Sambucus racemosa", "Roter Holunder", "", "Hirsch-Holunder"],
  ["Calystegia sepium", "Echte Zaunwinde", "Convolvulus sepium"],
  ["Myosotis scorpioides", "Sumpf-Vergissmeinnicht", "Myosotis palustris"],
  ["Solanum dulcamara", "Bittersüßer Nachtschatten"],
  ["Scrophularia nodosa", "Knotige Braunwurz"],
  ["Melampyrum pratense", "Wiesen-Wachtelweizen"],
  ["Plantago lanceolata", "Spitz-Wegerich"],
  ["Plantago major", "Breit-Wegerich"],
  ["Veronica chamaedrys", "Gamander-Ehrenpreis"],
  ["Digitalis purpurea", "Roter Fingerhut"],
  ["Ajuga reptans", "Kriechender Günsel"],
  ["Glechoma hederacea", "Gundermann"],
  ["Prunella vulgaris", "Gewöhnliche Braunelle", "", "Kleine Braunelle"],
  ["Galeopsis tetrahit", "Gewöhnlicher Hohlzahn"],
  ["Lamium album", "Weiße Taubnessel"],
  ["Lamium galeobdolon", "Goldnessel"],
  ["Lamium maculatum", "Gefleckte Taubnessel"],
  ["Stachys sylvatica", "Wald-Ziest"],
  ["Campanula patula", "Wiesen-Glockenblume"],
  ["Campanula rotundifolia", "Rundblättrige Glockenblume"],
  ["Tussilago farfara", "Huflattich"],
  ["Petasites hybridus", "Gewöhnliche Pestwurz"],
  ["Senecio ovatus", "Fuchssches Greiskraut", "Senecio fuchsii"],
  ["Solidago canadensis", "Kanadische Goldrute"],
  ["Bellis perennis", "Ausdauerndes Gänseblümchen"],
  ["Achillea millefolium agg.", "Gewöhnliche Schafgarbe", "Achillea millefolium"],
  ["Matricaria recutita", "Echte Kamille", "Matricaria chamomilla"],
  ["Tripleurospermum perforatum", "Geruchlose Kamille", "Matricaria inodorata"],
  ["Leucanthemum ircutianum", "Wiesen-Margerite"],
  ["Tanacetum vulgare", "Rainfarn", "Chrysanthemum vulgare"],
  ["Artemisia vulgaris", "Gewöhnlicher Beifuß"],
  ["Arctium lappa", "Große Klette"],
  ["Cirsium arvense", "Acker-Kratzdistel"],
  ["Cirsium oleraceum", "Kohl-Kratzdistel", "", "Kohldistel"],
  ["Cirsium palustre", "Sumpf-Kratzdistel"],
  ["Cirsium vulgare", "Gewöhnliche Kratzdistel"],
  ["Cyanus segetum", "Kornblume", "Centaurea cyanus"],
  ["Centaurea jacea", "Wiesen-Flockenblume"],
  ["Lapsana communis", "Rainkohl"],
  ["Hypochaeris radicata", "Gewöhnliches Ferkelkraut", "Hypochoeris radicata"],
  ["Scorzoneroides autumnalis", "Herbst-Löwenzahn"],
  ["Taraxacum officinale agg.", "Wiesen-Löwenzahn", "Taraxacum officinale", "Kuhblume"],
  ["Crepis biennis", "Wiesen-Pippau"],
  ["Hieracium lachenalii", "Gewöhnliches Habichtskraut"],
  ["Pilosella aurantiaca", "Orangerotes Habichtskraut"],
  ["Pilosella officinarum", "Kleines Habichtskraut", "Hieracium pilosella"],
  ["Potamogeton berchtoldii", "Berchtolds Laichkraut"],
  ["Potamogeton natans", "Schwimmendes Laichkraut"],
  ["Maianthemum bifolium", "Zweiblättrige Schattenblume"],
  ["Polygonatum multiflorum", "Vielblütige Weißwurz"],
  ["Convallaria majalis", "Maiglöckchen"],
  ["Iris pseudacorus", "Wasser-Schwertlilie", "", "Sumpf-Schwertlilie"],
  ["Juncus conglomeratus", "Knäuel-Binse"],
  ["Juncus effusus", "Flatter-Binse"],
  ["Luzula campestris", "Gewöhnliche Hainsimse", "", "Feld-Hainsimse|Hasenbrot"],
  ["Luzula luzuloides", "Schmalblättrige Hainsimse", "", "Weiße Hainsimse"],
  ["Scirpus sylvaticus", "Wald-Simse"],
  ["Carex acuta", "Schlank-Segge", "Carex gracilis"],
  ["Carex brizoides", "Zittergras-Segge", "", "Seegras"],
  ["Carex leporina", "Hasenpfoten-Segge"],
  ["Carex nigra", "Wiesen-Segge", "", "Braune Segge"],
  ["Carex pallescens", "Bleiche Segge"],
  ["Carex vesicaria", "Blasen-Segge"],
  ["Lolium multiflorum", "Welsches Weidelgras", "", "Italienisches Raygras"],
  ["Lolium perenne", "Deutsches Weidelgras", "", "Englisches Raygras"],
  ["Festuca gigantea", "Riesen-Schwingel"],
  ["Festuca ovina", "Schaf-Schwingel"],
  ["Festuca pratensis", "Wiesen-Schwingel"],
  ["Festuca rubra", "Roter Schwingel"],
  ["Poa annua", "Einjähriges Rispengras"],
  ["Poa nemoralis", "Hain-Rispengras"],
  ["Poa pratensis", "Wiesen-Rispengras"],
  ["Poa trivialis", "Gewöhnliches Rispengras"],
  ["Dactylis glomerata", "Wiesen-Knäuelgras"],
  ["Elymus repens", "Gewöhnliche Quecke", "Agropyron repens"],
  ["Calamagrostis epigejos", "Land-Reitgras"],
  ["Agrostis capillaris", "Rotes Straußgras", "Agrostis tenuis"],
  ["Agrostis stolonifera agg.", "Weißes Straußgras", "Agrostis stolonifera", "Flecht-Straußgras"],
  ["Arrhenatherum elatius", "Glatthafer"],
  ["Deschampsia cespitosa agg.", "Rasen-Schmiele", "Deschampsia cespitosa"],
  ["Deschampsia flexuosa", "Draht-Schmiele", "Avenella flexuosa", "Schlängel-Schmiele"],
  ["Holcus lanatus", "Wolliges Honiggras"],
  ["Holcus mollis", "Weiches Honiggras"],
  ["Milium effusum", "Flattergras"],
  ["Phleum pratense agg.", "Wiesen-Lieschgras", "Phleum pratense"],
  ["Alopecurus pratensis", "Wiesen-Fuchsschwanz"],
  ["Phalaris arundinacea", "Rohr-Glanzgras"],
  ["Anthoxanthum odoratum", "Gewöhnliches Ruchgras"],
  ["Phragmites australis", "Schilf", "Phragmites communis"],
  ["Lemna minor", "Kleine Wasserlinse"],
  ["Typha angustifolia", "Schmalblättriger Rohrkolben"],
  ["Typha latifolia", "Breitblättriger Rohrkolben"]
];

const ANIMALS = [
  ["Vanessa cardui", "Distelfalter"],
  ["Vanessa atalanta", "Admiral"],
  ["Nymphalis urticae", "Kleiner Fuchs", "Aglais urticae"],
  ["Nymphalis c-album", "C-Falter", "Polygonia c-album"],
  ["Nymphalis antiopa", "Trauermantel"],
  ["Nymphalis io", "Tagpfauenauge", "Inachis io|Aglais io"],
  ["Araschnia levana", "Landkärtchen"],
  ["Papilio machaon", "Schwalbenschwanz"],
  ["Gonepteryx rhamni", "Zitronenfalter"],
  ["Anthocharis cardamines", "Aurorafalter"],
  ["Pieris napi", "Rapsweißling", "", "Grünaderweißling|Heckenweißling"],
  ["Pieris rapae", "Kleiner Kohlweißling", "", "Rübenweißling"],
  ["Pieris brassicae", "Großer Kohlweißling"],
  ["Macroglossum stellatarum", "Taubenschwänzchen"],
  ["Anguilla anguilla", "Aal"],
  ["Esox lucius", "Hecht"],
  ["Cyprinus carpio", "Karpfen"],
  ["Salmo trutta fario", "Bachforelle", "Salmo trutta"],
  ["Oncorhynchus mykiss", "Regenbogenforelle", "Salmo gairdneri"],
  ["Gasterosteus aculeatus", "Dreistacheliger Stichling"],
  ["Rutilus rutilus", "Plötze", "", "Rotauge"],
  ["Tinca tinca", "Schleie"],
  ["Carassius carassius", "Karausche"],
  ["Leucaspius delineatus", "Moderlieschen", "Leucaspinus delineatus"],
  ["Gobio gobio", "Gründling"],
  ["Phoxinus phoxinus", "Elritze"],
  ["Bufo bufo", "Erdkröte"],
  ["Bombina bombina", "Rotbauchunke"],
  ["Hyla arborea", "Laubfrosch"],
  ["Rana temporaria", "Grasfrosch"],
  ["Pelophylax kl. esculentus", "Wasserfrosch", "Rana kl. esculenta|Rana esculenta"],
  ["Triturus cristatus", "Kammmolch"],
  ["Ichthyosaura alpestris", "Bergmolch", "Triturus alpestris"],
  ["Lissotriton vulgaris", "Teichmolch", "Triturus vulgaris"],
  ["Anguis fragilis", "Blindschleiche"],
  ["Natrix natrix", "Ringelnatter"],
  ["Coronella austriaca", "Schlingnatter", "", "Glattnatter"],
  ["Vipera berus", "Kreuzotter"],
  ["Zootoca vivipara", "Waldeidechse", "Lacerta vivipara"],
  ["Lacerta agilis", "Zauneidechse"],
  ["Podiceps cristatus", "Haubentaucher"],
  ["Tachybaptus ruficollis", "Zwergtaucher", "Podiceps ruficollis"],
  ["Phalacrocorax carbo", "Kormoran"],
  ["Ardea cinerea", "Graureiher"],
  ["Ardea alba", "Silberreiher", "Casmerodius albus|Egretta alba"],
  ["Botaurus stellaris", "Große Rohrdommel"],
  ["Ciconia ciconia", "Weißstorch"],
  ["Ciconia nigra", "Schwarzstorch"],
  ["Cygnus olor", "Höckerschwan"],
  ["Cygnus cygnus", "Singschwan"],
  ["Anser anser", "Graugans"],
  ["Anser fabalis", "Saatgans"],
  ["Anser albifrons", "Blessgans"],
  ["Anas platyrhynchos", "Stockente"],
  ["Spatula clypeata", "Löffelente", "Anas clypeata"],
  ["Anas crecca", "Krickente"],
  ["Spatula querquedula", "Knäkente", "Anas querquedula"],
  ["Aythya ferina", "Tafelente"],
  ["Aythya fuligula", "Reiherente"],
  ["Bucephala clangula", "Schellente"],
  ["Pandion haliaetus", "Fischadler"],
  ["Haliaeetus albicilla", "Seeadler"],
  ["Milvus milvus", "Rotmilan"],
  ["Milvus migrans", "Schwarzmilan"],
  ["Circus aeruginosus", "Rohrweihe"],
  ["Buteo buteo", "Mäusebussard"],
  ["Accipiter nisus", "Sperber"],
  ["Accipiter gentilis", "Habicht"],
  ["Falco tinnunculus", "Turmfalke"],
  ["Phasianus colchicus", "Fasan"],
  ["Perdix perdix", "Rebhuhn"],
  ["Gallinula chloropus", "Teichralle", "", "Teichhuhn"],
  ["Fulica atra", "Blessralle", "", "Blesshuhn"],
  ["Rallus aquaticus", "Wasserralle"],
  ["Grus grus", "Kranich"],
  ["Vanellus vanellus", "Kiebitz"],
  ["Numenius arquata", "Großer Brachvogel"],
  ["Chroicocephalus ridibundus", "Lachmöwe", "Larus ridibundus"],
  ["Columba palumbus", "Ringeltaube"],
  ["Streptopelia decaocto", "Türkentaube"],
  ["Cuculus canorus", "Kuckuck"],
  ["Tyto alba", "Schleiereule"],
  ["Bubo bubo", "Uhu"],
  ["Strix aluco", "Waldkauz"],
  ["Asio otus", "Waldohreule"],
  ["Apus apus", "Mauersegler"],
  ["Alcedo atthis", "Eisvogel"],
  ["Dendrocopos major", "Buntspecht"],
  ["Picus viridis", "Grünspecht"],
  ["Dryocopus martius", "Schwarzspecht"],
  ["Hirundo rustica", "Rauchschwalbe"],
  ["Delichon urbicum", "Mehlschwalbe", "Delichon urbica"],
  ["Alauda arvensis", "Feldlerche"],
  ["Motacilla alba", "Bachstelze"],
  ["Motacilla cinerea", "Gebirgsstelze"],
  ["Troglodytes troglodytes", "Zaunkönig"],
  ["Cinclus cinclus", "Wasseramsel"],
  ["Erithacus rubecula", "Rotkehlchen"],
  ["Phoenicurus ochruros", "Hausrotschwanz"],
  ["Phoenicurus phoenicurus", "Gartenrotschwanz"],
  ["Turdus merula", "Amsel"],
  ["Turdus philomelos", "Singdrossel", "Turdus philomelus"],
  ["Turdus pilaris", "Wacholderdrossel"],
  ["Sylvia atricapilla", "Mönchsgrasmücke"],
  ["Phylloscopus collybita", "Zilpzalp"],
  ["Phylloscopus trochilus", "Fitis"],
  ["Regulus ignicapilla", "Sommergoldhähnchen", "Regulus ignicapillus"],
  ["Regulus regulus", "Wintergoldhähnchen"],
  ["Periparus ater", "Tannenmeise", "Parus ater"],
  ["Lophophanes cristatus", "Haubenmeise", "Parus cristatus"],
  ["Cyanistes caeruleus", "Blaumeise", "Parus caeruleus"],
  ["Parus major", "Kohlmeise"],
  ["Sitta europaea", "Kleiber"],
  ["Garrulus glandarius", "Eichelhäher"],
  ["Corvus corone", "Rabenkrähe", "Corvus corone corone", "Aaskrähe"],
  ["Corvus cornix", "Nebelkrähe", "Corvus corone cornix"],
  ["Corvus corax", "Kolkrabe"],
  ["Coloeus monedula", "Dohle", "Corvus monedula"],
  ["Corvus frugilegus", "Saatkrähe"],
  ["Pica pica", "Elster"],
  ["Sturnus vulgaris", "Star"],
  ["Passer domesticus", "Haussperling"],
  ["Passer montanus", "Feldsperling"],
  ["Chloris chloris", "Grünfink", "Carduelis chloris", "Grünling"],
  ["Carduelis carduelis", "Stieglitz", "", "Distelfink"],
  ["Spinus spinus", "Erlenzeisig", "Carduelis spinus", "Zeisig"],
  ["Coccothraustes coccothraustes", "Kernbeißer"],
  ["Fringilla coelebs", "Buchfink"],
  ["Pyrrhula pyrrhula", "Gimpel", "", "Dompfaff"],
  ["Emberiza citrinella", "Goldammer"],
  ["Talpa europaea", "Maulwurf"],
  ["Erinaceus europaeus", "Europäischer Igel", "", "Igel"],
  ["Lepus europaeus", "Feldhase"],
  ["Oryctolagus cuniculus", "Kaninchen"],
  ["Cricetus cricetus", "Feldhamster"],
  ["Sciurus vulgaris", "Eichhörnchen"],
  ["Castor fiber", "Biber"],
  ["Glis glis", "Siebenschläfer"],
  ["Martes foina", "Steinmarder"],
  ["Martes martes", "Baummarder"],
  ["Mustela putorius", "Iltis"],
  ["Mustela erminea", "Hermelin"],
  ["Mustela nivalis", "Mauswiesel"],
  ["Meles meles", "Dachs"],
  ["Vulpes vulpes", "Fuchs"],
  ["Lutra lutra", "Fischotter"],
  ["Sus scrofa", "Wildschwein"],
  ["Cervus elaphus", "Rothirsch"],
  ["Dama dama", "Damhirsch", "Cervus dama"],
  ["Capreolus capreolus", "Reh"],
  ["Ovis ammon", "Mufflon"]
];

// [latin, german, rank, comparison group, latin aliases, german aliases, image query]
const GROUP_TAXA = [
  ["Platyhelminthes", "Plattwürmer", "Stamm", "major-phyla"],
  ["Aschelminthes", "Rundwürmer", "Stamm", "major-phyla", "Nematoda", "", "Nematoda"],
  ["Mollusca", "Weichtiere", "Stamm", "major-phyla"],
  ["Annelida", "Ringelwürmer", "Stamm", "major-phyla"],
  ["Arthropoda", "Gliederfüßer", "Stamm", "major-phyla"],
  ["Chordata", "Chordatiere", "Stamm", "major-phyla"],
  ["Crustacea", "Krebstiere", "Unterstamm", "major-subphyla"],
  ["Tracheata", "Tracheentiere", "Unterstamm", "major-subphyla"],
  ["Vertebrata", "Wirbeltiere", "Unterstamm", "major-subphyla"],
  ["Turbellaria", "Strudelwürmer", "Klasse", "invertebrate-classes"],
  ["Rotatoria", "Rädertierchen", "Klasse", "invertebrate-classes", "Rotifera", "", "Rotifera"],
  ["Bivalvia", "Muscheln", "Klasse", "invertebrate-classes"],
  ["Gastropoda", "Schnecken", "Klasse", "invertebrate-classes"],
  ["Arachnida", "Spinnentiere", "Klasse", "invertebrate-classes"],
  ["Phyllopoda", "Blattfußkrebse", "Klasse", "invertebrate-classes", "Branchiopoda", "", "Branchiopoda"],
  ["Malacostraca", "Höhere Krebse", "Klasse", "invertebrate-classes"],
  ["Myriapoda", "Tausendfüßer", "Klasse", "invertebrate-classes"],
  ["Insecta", "Insekten", "Klasse", "invertebrate-classes"],
  ["Pisces", "Fische", "Klasse", "vertebrate-classes", "Actinopterygii", "", "Actinopterygii"],
  ["Amphibia", "Amphibien", "Klasse", "vertebrate-classes"],
  ["Reptilia", "Reptilien", "Klasse", "vertebrate-classes"],
  ["Aves", "Vögel", "Klasse", "vertebrate-classes"],
  ["Mammalia", "Säugetiere", "Klasse", "vertebrate-classes"],
  ["Chilopoda", "Hundertfüßer", "Unterklasse", "myriapod-subclasses"],
  ["Diplopoda", "Doppelfüßer", "Unterklasse", "myriapod-subclasses"],
  ["Anisoptera", "Großlibellen", "Unterordnung", "small-invertebrate-suborders"],
  ["Zygoptera", "Kleinlibellen", "Unterordnung", "small-invertebrate-suborders"],
  ["Amphipoda", "Flohkrebse", "Unterordnung", "small-invertebrate-suborders"],
  ["Isopoda", "Asseln", "Unterordnung", "small-invertebrate-suborders"],
  ["Basommatophora", "Süßwasser-Lungenschnecken", "Ordnung", "small-invertebrate-orders", "Hygrophila", "", "Hygrophila"],
  ["Stylommatophora", "Land-Lungenschnecken", "Ordnung", "small-invertebrate-orders"],
  ["Oligochaeta", "Wenigborster", "Ordnung", "small-invertebrate-orders"],
  ["Hirudinea", "Egel", "Ordnung", "small-invertebrate-orders"],
  ["Opiliones", "Weberknechte", "Ordnung", "arachnid-orders"],
  ["Araneae", "Webspinnen", "Ordnung", "arachnid-orders"],
  ["Acari", "Milben", "Ordnung", "arachnid-orders"],
  ["Ephemeroptera", "Eintagsfliegen", "Ordnung", "insect-orders"],
  ["Odonata", "Libellen", "Ordnung", "insect-orders"],
  ["Ensifera", "Langfühlerschrecken", "Ordnung", "insect-orders", "", "", "Ensifera"],
  ["Caelifera", "Kurzfühlerschrecken", "Ordnung", "insect-orders", "", "", "Caelifera"],
  ["Dermaptera", "Ohrwürmer", "Ordnung", "insect-orders"],
  ["Heteroptera", "Wanzen", "Ordnung", "insect-orders"],
  ["Auchenorrhyncha", "Zikaden", "Ordnung", "insect-orders"],
  ["Aphidina", "Blattläuse", "Ordnung", "insect-orders", "Aphidoidea", "", "Aphidoidea"],
  ["Psyllina", "Blattflöhe", "Ordnung", "insect-orders", "Psylloidea", "", "Psylloidea"],
  ["Mecoptera", "Schnabelfliegen", "Ordnung", "insect-orders"],
  ["Neuroptera", "Netzflügler", "Ordnung", "insect-orders"],
  ["Diptera", "Zweiflügler", "Ordnung", "insect-orders"],
  ["Coleoptera", "Käfer", "Ordnung", "insect-orders"],
  ["Trichoptera", "Köcherfliegen", "Ordnung", "insect-orders"],
  ["Hymenoptera", "Hautflügler", "Ordnung", "insect-orders"],
  ["Lepidoptera", "Schmetterlinge", "Ordnung", "insect-orders"],
  ["Podicipediformes", "Lappentaucher", "Ordnung", "bird-orders"],
  ["Pelecaniformes", "Ruderfüßer", "Ordnung", "bird-orders"],
  ["Ciconiiformes", "Schreitvögel", "Ordnung", "bird-orders"],
  ["Anseriformes", "Entenvögel", "Ordnung", "bird-orders"],
  ["Accipitriformes", "Greifvögel", "Ordnung", "bird-orders"],
  ["Galliformes", "Hühnervögel", "Ordnung", "bird-orders"],
  ["Gruiformes", "Kranichvögel", "Ordnung", "bird-orders"],
  ["Charadriiformes", "Wat-, Möwen- und Alkenvögel", "Ordnung", "bird-orders"],
  ["Columbiformes", "Tauben", "Ordnung", "bird-orders"],
  ["Cuculiformes", "Kuckucke", "Ordnung", "bird-orders"],
  ["Strigiformes", "Eulen", "Ordnung", "bird-orders"],
  ["Apodiformes", "Segler", "Ordnung", "bird-orders"],
  ["Coraciiformes", "Rackenvögel", "Ordnung", "bird-orders"],
  ["Piciformes", "Spechtvögel", "Ordnung", "bird-orders"],
  ["Passeriformes", "Singvögel", "Ordnung", "bird-orders"],
  ["Insectivora", "Insektenfresser", "Ordnung", "mammal-orders", "Eulipotyphla", "", "Eulipotyphla"],
  ["Chiroptera", "Fledermäuse", "Ordnung", "mammal-orders"],
  ["Lagomorpha", "Hasentiere", "Ordnung", "mammal-orders"],
  ["Rodentia", "Nagetiere", "Ordnung", "mammal-orders"],
  ["Carnivora", "Raubtiere", "Ordnung", "mammal-orders"],
  ["Artiodactyla", "Paarhufer", "Ordnung", "mammal-orders"],
  ["Lymnaeidae", "Schlammschnecken", "Familie", "worm-mollusc-families"],
  ["Succineidae", "Bernsteinschnecken", "Familie", "worm-mollusc-families"],
  ["Helicidae", "Schnirkelschnecken", "Familie", "worm-mollusc-families"],
  ["Arionidae", "Wegschnecken", "Familie", "worm-mollusc-families"],
  ["Lumbricidae", "Regenwürmer", "Familie", "worm-mollusc-families"],
  ["Erpobdellidae", "Rollegel", "Familie", "worm-mollusc-families"],
  ["Araneidae", "Radnetzspinnen", "Familie", "spider-families"],
  ["Salticidae", "Springspinnen", "Familie", "spider-families", "Saltidae"],
  ["Lycosidae", "Wolfsspinnen", "Familie", "spider-families"],
  ["Pentatomidae", "Baumwanzen", "Familie", "true-bug-families"],
  ["Miridae", "Weichwanzen", "Familie", "true-bug-families"],
  ["Carabidae", "Laufkäfer", "Familie", "beetle-families"],
  ["Coccinellidae", "Marienkäfer", "Familie", "beetle-families"],
  ["Scarabaeidae", "Blatthornkäfer", "Familie", "beetle-families"],
  ["Lucanidae", "Hirschkäfer", "Familie", "beetle-families", "", "Schröter"],
  ["Cerambycidae", "Bockkäfer", "Familie", "beetle-families"],
  ["Chrysomelidae", "Blattkäfer", "Familie", "beetle-families"],
  ["Curculionidae", "Rüsselkäfer", "Familie", "beetle-families"],
  ["Elateridae", "Schnellkäfer", "Familie", "beetle-families"],
  ["Staphylinidae", "Kurzflügler", "Familie", "beetle-families", "", "Kurzflügelkäfer"],
  ["Formicidae", "Ameisen", "Familie", "hymenoptera-families"],
  ["Apidae", "Bienen", "Familie", "hymenoptera-families", "", "Hummeln"],
  ["Hesperiidae", "Dickkopffalter", "Familie", "butterfly-families", "", "Dickköpfe"],
  ["Zygaenidae", "Widderchen", "Familie", "butterfly-families"],
  ["Nymphalidae", "Edel- und Augenfalter", "Familie", "butterfly-families"],
  ["Papilionidae", "Schwalbenschwänze", "Familie", "butterfly-families", "", "Ritter"],
  ["Lycaenidae", "Bläulinge und Würfelfalter", "Familie", "butterfly-families"],
  ["Pieridae", "Weißlinge", "Familie", "butterfly-families"],
  ["Noctuidae", "Eulenfalter", "Familie", "moth-families"],
  ["Geometridae", "Spanner", "Familie", "moth-families"],
  ["Sphingidae", "Schwärmer", "Familie", "moth-families"],
  ["Soricidae", "Spitzmäuse", "Familie", "mammal-families"],
  ["Talpidae", "Maulwürfe", "Familie", "mammal-families"],
  ["Erinaceidae", "Igel", "Familie", "mammal-families"],
  ["Muridae", "Echte Mäuse", "Familie", "mammal-families", "", "Langschwanzmäuse"],
  ["Cricetidae", "Hamsterartige", "Familie", "mammal-families"],
  ["Arvicolidae", "Wühlmäuse", "Familie", "mammal-families", "", "Kurzschwanzmäuse"],
  ["Sciuridae", "Hörnchen", "Familie", "mammal-families"],
  ["Castoridae", "Biber", "Familie", "mammal-families"],
  ["Gliridae", "Schläfer", "Familie", "mammal-families"]
];

const GENUS_CLUSTERS = [
  ["ferns", "Equisetum Pteridium Athyrium Dryopteris"],
  ["conifers", "Abies Pseudotsuga Picea Larix Pinus"],
  ["aquatic-plants", "Nuphar Nymphaea Potamogeton Lemna Typha Phragmites Iris"],
  ["buttercups", "Anemone Caltha Ficaria Ranunculus"],
  ["showy-field-forbs", "Chelidonium Papaver Hypericum Euphorbia Mercurialis"],
  ["oaks-and-beech", "Fagus Quercus Carpinus"],
  ["birch-hazel-trees", "Betula Alnus Corylus Ulmus"],
  ["deciduous-trees", "Populus Salix Tilia Acer Aesculus Fraxinus Robinia"],
  ["small-white-forbs", "Urtica Stellaria Cerastium Moehringia Lychnis Silene Chenopodium Galium"],
  ["docks-and-knotweeds", "Rumex Fallopia Bistorta"],
  ["brassicas", "Alliaria Cardamine Capsella Thlaspi Noccaea"],
  ["woodland-groundcover", "Viola Oxalis Fragaria Hedera Calluna Vaccinium"],
  ["primrose-like", "Lysimachia Primula Filipendula Geum"],
  ["rosaceous-woody", "Rosa Rubus Pyrus Malus Sorbus Crataegus Prunus Ribes"],
  ["legumes", "Cytisus Melilotus Trifolium Lotus Vicia Lathyrus"],
  ["balsams-and-cranesbills", "Impatiens Geranium Epilobium"],
  ["umbellifers", "Anthriscus Aegopodium Meum Heracleum Daucus"],
  ["shrubs-and-climbers", "Euonymus Frangula Viscum Sambucus Calystegia Solanum"],
  ["figworts-and-plantains", "Scrophularia Melampyrum Plantago Veronica Digitalis Myosotis"],
  ["mints", "Ajuga Glechoma Prunella Galeopsis Lamium Stachys"],
  ["bellflowers", "Campanula Viola Myosotis"],
  ["early-yellow-asters", "Tussilago Petasites Senecio Solidago"],
  ["daisy-asters", "Bellis Achillea Matricaria Tripleurospermum Leucanthemum Tanacetum Artemisia"],
  ["thistles", "Arctium Cirsium Cyanus Centaurea"],
  ["dandelion-asters", "Lapsana Hypochaeris Scorzoneroides Taraxacum Crepis Hieracium Pilosella"],
  ["lily-like-monocots", "Maianthemum Polygonatum Convallaria Iris"],
  ["rushes-and-sedges", "Juncus Luzula Scirpus Carex"],
  ["grasses", "Lolium Festuca Poa Dactylis Elymus Calamagrostis Agrostis Arrhenatherum Deschampsia Holcus Milium Phleum Alopecurus Phalaris Anthoxanthum Phragmites"],
  ["butterflies", "Vanessa Nymphalis Araschnia Papilio Gonepteryx Anthocharis Pieris Macroglossum"],
  ["fish", "Anguilla Esox Cyprinus Salmo Oncorhynchus Gasterosteus Rutilus Tinca Carassius Leucaspius Gobio Phoxinus"],
  ["amphibians", "Bufo Bombina Hyla Rana Pelophylax Triturus Ichthyosaura Lissotriton"],
  ["reptiles", "Anguis Natrix Coronella Vipera Zootoca Lacerta"],
  ["diving-waterbirds", "Podiceps Tachybaptus Phalacrocorax"],
  ["herons-and-storks", "Ardea Botaurus Ciconia"],
  ["waterfowl", "Cygnus Anser Anas Spatula Aythya Bucephala"],
  ["raptors", "Pandion Haliaeetus Milvus Circus Buteo Accipiter Falco"],
  ["ground-and-wetland-birds", "Phasianus Perdix Gallinula Fulica Rallus Grus Vanellus Numenius Chroicocephalus"],
  ["pigeons-cuckoos-swifts", "Columba Streptopelia Cuculus Apus"],
  ["owls", "Tyto Bubo Strix Asio"],
  ["woodpeckers-and-kingfisher", "Alcedo Dendrocopos Picus Dryocopus"],
  ["open-country-songbirds", "Hirundo Delichon Alauda Motacilla Troglodytes Cinclus"],
  ["small-songbirds", "Erithacus Phoenicurus Turdus Sylvia Phylloscopus Regulus"],
  ["tits-and-nuthatch", "Periparus Lophophanes Cyanistes Parus Sitta"],
  ["corvids", "Garrulus Corvus Coloeus Pica"],
  ["finches-and-sparrows", "Sturnus Passer Chloris Carduelis Spinus Coccothraustes Fringilla Pyrrhula Emberiza"],
  ["small-mammals", "Talpa Erinaceus Lepus Oryctolagus Cricetus Sciurus Castor Glis"],
  ["carnivores", "Martes Mustela Meles Vulpes Lutra"],
  ["ungulates", "Sus Cervus Dama Capreolus Ovis"]
];

const GENUS_CLUSTER = Object.fromEntries(GENUS_CLUSTERS.flatMap(([cluster, genera]) =>
  genera.split(" ").map(genus => [genus, cluster])));

const splitAliases = value => value ? value.split("|").map(item => item.trim()) : [];
const makeSpecies = (rows, group) => rows.map(([latin, german, latinAliases = "", germanAliases = ""], index) => ({
  id: `${group}-${index}`,
  group,
  kind: "species",
  cluster: GENUS_CLUSTER[latin.split(" ")[0]] || `${group}-other`,
  latin,
  german,
  latinAliases: splitAliases(latinAliases),
  germanAliases: splitAliases(germanAliases)
}));

const makeTaxa = rows => rows.map(([latin, german, rank, cluster, latinAliases = "", germanAliases = "", imageName = ""], index) => ({
  id: `taxon-${index}`,
  group: "animal",
  kind: "taxon",
  rank,
  cluster,
  latin,
  german,
  imageName,
  latinAliases: splitAliases(latinAliases),
  germanAliases: splitAliases(germanAliases)
}));

const SPECIES = [...makeSpecies(PLANTS, "plant"), ...makeSpecies(ANIMALS, "animal"), ...makeTaxa(GROUP_TAXA)];
